modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_tournament"
version = "${version}"
displayName = "VS Tournament Mod"
authors = [
    "ConstantDust",
    "alex_s168"
]
description = '''

'''
logoFile = "icon.png"

[[dependencies.vs_tournament]]
modId = "forge"
mandatory = false
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "valkyrienskies"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "architectury"
mandatory = false
versionRange = "[1.31.61,)"
ordering = "AFTER"
side = "BOTH"
